/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "Docs",
  "tagline": "Документация проекта",
  "url": "https://undefined.pages.devplatform.tcsbank.ru",
  "baseUrl": "/",
  "onBrokenLinks": "throw",
  "onBrokenMarkdownLinks": "warn",
  "markdown": {
    "mermaid": true,
    "format": "mdx",
    "mdx1Compat": {
      "comments": true,
      "admonitions": true,
      "headingIds": true
    },
    "anchors": {
      "maintainCase": false
    }
  },
  "favicon": "img/favicon.png",
  "organizationName": "tinkoff",
  "projectName": "Docs",
  "customFields": {
    "GLOBAL_CONFIG": {
      "disableIntegrations": false,
      "useLegacyKrokiImgRefDir": false,
      "title": "Docs",
      "description": "",
      "baseUrl": "/",
      "publicPath": "https://undefined.pages.devplatform.tcsbank.ru/",
      "footerLinks": [
        {
          "title": "More",
          "items": [
            {
              "label": "📖 Собери такую документацию за 5 минут 🎉",
              "href": "https://unic.pages.devplatform.tcsbank.ru/pipelines/docs/features/auto-doc",
              "data-track": "footer-more-autodoc"
            },
            {
              "label": "🤖 Nestor — как copilot, только свой 🦾",
              "title": "Наш внутренний ассистент при работе с кодом для Copilot-like автодополнения и упрощения работы с нашей инфраструктурой",
              "href": "https://wiki.tcsbank.ru/display/CORE/AI+Assistant+-+Nestor",
              "data-track": "footer-more-nestor"
            }
          ]
        }
      ],
      "apiSchemas": [],
      "blogExist": false
    }
  },
  "presets": [
    [
      "classic",
      {
        "docs": {
          "sidebarPath": "/Users/s.v.kuzmin/.nvm/versions/node/v22.16.0/lib/node_modules/@unic/autodoc-cli/sidebars.js",
          "editUrl": "https://gitlab.tcsbank.ru//-/edit/master",
          "showLastUpdateAuthor": true,
          "showLastUpdateTime": true,
          "remarkPlugins": [
            [
              null,
              {
                "baseUrl": "https://kroki.tcsbank.ru/plantuml/png"
              }
            ],
            [
              null,
              {
                "krokiBase": "https://kroki.tcsbank.ru",
                "lang": "kroki",
                "imgRefDir": "/img/kroki",
                "imgDir": "static/img/kroki"
              }
            ]
          ]
        },
        "theme": {
          "customCss": "/Users/s.v.kuzmin/.nvm/versions/node/v22.16.0/lib/node_modules/@unic/autodoc-cli/src/css/custom.css"
        },
        "pages": {
          "path": "/Users/s.v.kuzmin/.nvm/versions/node/v22.16.0/lib/node_modules/@unic/autodoc-cli/src/pages"
        }
      }
    ]
  ],
  "themes": [
    "@docusaurus/theme-mermaid"
  ],
  "themeConfig": {
    "navbar": {
      "title": "Docs",
      "logo": {
        "alt": "Docs",
        "src": "img/logo.svg",
        "srcDark": "img/logo-dark.svg"
      },
      "items": [
        {
          "type": "docSidebar",
          "sidebarId": ".",
          "label": "Документация",
          "position": "left"
        },
        {
          "href": "https://gitlab.tcsbank.ru/",
          "label": "Репозиторий",
          "position": "right"
        },
        {
          "type": "html",
          "position": "right",
          "value": " ",
          "className": "navbar-separator"
        },
        {
          "type": "html",
          "value": "<a href=\"https://wiki.tcsbank.ru/display/CORE/AI+Assistant+-+Nestor\" target=\"_blank\" title=\"Наш внутренний ассистент при работе с кодом для Copilot-like автодополнения и упрощения работы с нашей инфраструктурой\" data-track=\"nestor\" class=\"button button--secondary\">Nestor</a>",
          "position": "right"
        },
        {
          "type": "html",
          "value": "<a href=\"/global-search\" title=\"поиск по всем документациям autodoc\" data-track=\"global-search\" class=\"button button--info\">Искать везде</a>",
          "position": "right"
        },
        {
          "type": "html",
          "position": "right",
          "value": " ",
          "className": "navbar-separator"
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "style": "light",
      "links": [
        {
          "title": "More",
          "items": [
            {
              "label": "📖 Собери такую документацию за 5 минут 🎉",
              "href": "https://unic.pages.devplatform.tcsbank.ru/pipelines/docs/features/auto-doc",
              "data-track": "footer-more-autodoc"
            },
            {
              "label": "🤖 Nestor — как copilot, только свой 🦾",
              "title": "Наш внутренний ассистент при работе с кодом для Copilot-like автодополнения и упрощения работы с нашей инфраструктурой",
              "href": "https://wiki.tcsbank.ru/display/CORE/AI+Assistant+-+Nestor",
              "data-track": "footer-more-nestor"
            }
          ]
        }
      ],
      "copyright": "Copyright © 2025 Tinkoff. Built with Docusaurus and <a href=\"https://unic.pages.devplatform.tcsbank.ru/pipelines/docs/features/auto-doc\" target=\"_blank\" data-track=\"footer-autodoc\">AutoDocs</a> by <a href=\"https://wiki.tcsbank.ru/display/core/frontend\" data-track=\"footer-coretech\" target=\"_blank\">CoreTech Frontend</a>."
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "additionalLanguages": [
        "kotlin",
        "java",
        "scala",
        "csharp",
        "swift",
        "toml",
        "rust"
      ],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": false
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "metadata": [],
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    },
    "mermaid": {
      "theme": {
        "dark": "dark",
        "light": "default"
      },
      "options": {}
    }
  },
  "plugins": [
    [
      "/Users/s.v.kuzmin/.nvm/versions/node/v22.16.0/lib/node_modules/@unic/autodoc-cli/node_modules/@easyops-cn/docusaurus-search-local/dist/server/server/index.js",
      {
        "hashed": true,
        "indexPages": true,
        "indexBlog": true,
        "language": [
          "en",
          "ru"
        ],
        "highlightSearchTermsOnTargetPage": true
      }
    ],
    [
      "/Users/s.v.kuzmin/.nvm/versions/node/v22.16.0/lib/node_modules/@unic/autodoc-cli/tools/plugins/plantuml/index.js",
      {
        "plantumlVersion": "1.2022.6"
      }
    ],
    [
      "drawio",
      {
        "lib": "/docusaurus-plugin-drawio/viewer.min.js"
      }
    ],
    null
  ],
  "staticDirectories": [
    "static",
    "/Users/s.v.kuzmin/.nvm/versions/node/v22.16.0/lib/node_modules/@unic/autodoc-cli/static"
  ],
  "baseUrlIssueBanner": true,
  "i18n": {
    "defaultLocale": "en",
    "path": "i18n",
    "locales": [
      "en"
    ],
    "localeConfigs": {}
  },
  "future": {
    "experimental_storage": {
      "type": "localStorage",
      "namespace": false
    },
    "experimental_router": "browser"
  },
  "onBrokenAnchors": "warn",
  "onDuplicateRoutes": "warn",
  "scripts": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false
};
